name: Build Hugo - WITH CACHE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code from https://github.com/gohugoio/hugo.git
        uses: actions/checkout@v2
        with:
          repository: gohugoio/hugo
          ref: stable

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build the Hugo executable
        run: go install --tags extended

      - name: Upload Hugo executable
        uses: actions/upload-artifact@v2
        with:
          name: hugo
          path: ~/go/bin/hugo
